compile1:
# 	Compile your code for first part here
  gcc Q1_part1.c

run1: compile1
# 	 Execute part 1 here
  ./a.out

compile2:
# 	Compile your code for second part here
  gcc Q1_part2.c -pthread
  
run2: compile2
#	Execute part 2 here
  ./a.out
